import { ChainId } from '@tentou-tech/uniswap-sdk-core'

export const TESTNETS = [
  ChainId.ARBITRUM_GOERLI,
  ChainId.POLYGON_MUMBAI,
  ChainId.GOERLI,
  ChainId.SEPOLIA,
  ChainId.CELO_ALFAJORES,
  ChainId.BASE_GOERLI,
  ChainId.OPTIMISM_SEPOLIA,
  ChainId.OPTIMISM_GOERLI,
  ChainId.ARBITRUM_SEPOLIA,
  ChainId.ARBITRUM_GOERLI,
  ChainId.UNICHAIN_SEPOLIA,
  ChainId.MONAD_TESTNET,
  ChainId.ARBITRUM_ONE,
  ChainId.ZORA,
  ChainId.BNB,
  ChainId.BLAST,
  ChainId.OPTIMISM,
  ChainId.POLYGON,
  ChainId.CELO,
  ChainId.GNOSIS,
  ChainId.MOONBEAM,
  ChainId.AVALANCHE,
  ChainId.BASE,
  ChainId.ZKSYNC,
  ChainId.WORLDCHAIN,
  ChainId.SONEIUM,
]
