name: build test

on:
  push:
    branches: [ dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build